// Generated by LiveScript 1.3.1
var start, isBlink, isLight, isRun, isShow, isWarned, handler, latency, stopBy, delay, audioRemind, audioEnd, newAudio, soundToggle, show, adjust, toggle, reset, blink, count, run;

// == 新增功能：進度條動畫與爆炸 ==
var initialSeconds = null;
function updateTimerBar() {
  var $bar = $('#timer-bar');
  var $explosion = $('#explosion');
  if (initialSeconds === null || initialSeconds === 0) {
    initialSeconds = delay > 0 ? delay : 1000;
  }
  var percent = (delay > 0 ? delay : 0) / initialSeconds;
  $bar.css('width', (percent * 100) + '%');
  // 顏色調整
  var color;
  if (percent > 0.5)      color = '#4caf50'; // 綠
  else if (percent > 0.2) color = '#ffeb3b'; // 黃
  else if (percent > 0.1) color = '#ff9800'; // 橙
  else                    color = '#f44336'; // 紅
  $bar.css('background', color);
  if (percent === 0) {
    $explosion.show();
    $('#timer-bar-bg').hide();
  } else {
    $explosion.hide();
    $('#timer-bar-bg').show();
  }
}

start = null;
isBlink = false;
isLight = true;
isRun = false;
isShow = true;
isWarned = false;
handler = null;
latency = 0;
stopBy = null;
delay = 60000;
audioRemind = null;
audioEnd = null;

newAudio = function(file){
  var x$, node;
  x$ = node = new Audio();
  x$.src = file;
  x$.loop = false;
  x$.load();
  document.body.appendChild(node);
  return node;
};

soundToggle = function(des, state){
  var x$;
  if (state) {
    return des.play();
  } else {
    x$ = des;
    x$.currentTime = 0;
    x$.pause();
    return x$;
  }
};

show = function(){
  isShow = !isShow;
  return $('.fbtn').css('opacity', isShow ? '1.0' : '0.1');
};

adjust = function(it, v){
  if (isBlink) {
    return;
  }
  delay = delay + it * 1000;
  if (it === 0) {
    delay = v * 1000;
    initialSeconds = delay;
  }
  if (delay <= 0) {
    delay = 0;
  }
  $('#timer').text(Math.ceil(Math.max(delay, 0) / 1000)); // 顯示剩餘秒數
  updateTimerBar();
  // 不再自動 resize 字型，完全用 css 控制
};

toggle = function(){
  isRun = !isRun;
  $('#toggle').text(isRun ? "STOP" : "RUN");
  if (!isRun && handler) {
    stopBy = new Date();
    clearInterval(handler);
    handler = null;
    soundToggle(audioEnd, false);
    soundToggle(audioRemind, false);
  }
  if (stopBy) {
    latency = latency + new Date().getTime() - stopBy.getTime();
  }
  if (isRun) {
    return run();
  }
};

reset = function(){
  if (delay === 0) {
    delay = 1000;
  }
  initialSeconds = delay;
  soundToggle(audioRemind, false);
  soundToggle(audioEnd, false);
  stopBy = 0;
  isWarned = false;
  isBlink = false;
  latency = 0;
  start = null;
  isRun = true;
  toggle();
  if (handler) {
    clearInterval(handler);
  }
  handler = null;
  $('#timer').text(Math.ceil(Math.max(delay, 0) / 1000)); // 秒數
  $('#timer').css('color', '#fff');
  updateTimerBar();
  // 不再 resize 字型
};

blink = function(){
  isBlink = true;
  isLight = !isLight;
  return $('#timer').css('color', isLight ? '#fff' : '#f00');
};

count = function(){
  var tm, diff;
  tm = $('#timer');
  diff = start.getTime() - new Date().getTime() + delay + latency;
  if (diff > 60000) {
    isWarned = false;
  }
  if (diff < 60000 && !isWarned) {
    isWarned = true;
    soundToggle(audioRemind, true);
  }
  if (diff < 55000) {
    soundToggle(audioRemind, false);
  }
  if (diff < 0 && !isBlink) {
    soundToggle(audioEnd, true);
    isBlink = true;
    diff = 0;
    clearInterval(handler);
    handler = setInterval(function(){
      return blink();
    }, 500);
  }
  tm.text(Math.ceil(Math.max(diff, 0) / 1000)); // 顯示秒數
  delay = diff;
  updateTimerBar();
  // 不再 resize 字型
};

run = function(){
  if (start === null) {
    start = new Date();
    latency = 0;
    isBlink = false;
    initialSeconds = delay;
    updateTimerBar();
  }
  if (handler) {
    clearInterval(handler);
  }
  if (isBlink) {
    return handler = setInterval(function(){
      return blink();
    }, 500);
  } else {
    return handler = setInterval(function(){
      return count();
    }, 100);
  }
};

// 如果你不用 resize，可以直接移除下方函數
resize = function(){};

window.onload = function(){
  $('#timer').text(Math.ceil(Math.max(delay, 0) / 1000)); // 秒數
  audioRemind = newAudio('audio/smb_warning.mp3');
  audioEnd = newAudio('audio/smb_mariodie.mp3');
  updateTimerBar();
  // 不再 resize 字型
};

window.onresize = function(){
  // 不再 resize
};
